export { default as apiCall } from './api'
export { authAPI } from './api'
export { default as coursesAPI } from './courses'
export { default as cohortsAPI } from './cohorts'
export { default as studentsAPI } from './students'
export { default as trainersAPI } from './trainers'
export { default as assignmentsAPI } from './assignments'
export { default as submissionsAPI } from './submissions'
export { default as sessionsAPI } from './sessions'
export { default as attendanceAPI } from './attendance'
export { default as resourcesAPI } from './resources'

